whole_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 1
## WRIST ONLY ISN'T A CHAIN SO DOESN'T HAVE IK. ONLY USED FOR NAMED POSES.
# wrist_only:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 1
# gripper:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 1
gripper:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
# sucker:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 1
# sucker:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 1
sucker:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  #position_only_ik: false
  #use_approximate_ik: true
realsense:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  position_only_ik: true
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
