# Settings for ros_control control loop
hardware_control_loop:
    loop_hz: 50

# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - x_axis_joint
        - y_axis_joint
        - z_axis_joint
        - yaw_joint
        - roll_joint
        - pitch_joint

# Publish all joint states ----------------------------------
joint_state_controller:
    type:         joint_state_controller/JointStateController
    publish_rate: 50

# Publish wrench ----------------------------------
force_torque_sensor_controller:
    type:         force_torque_sensor_controller/ForceTorqueSensorController
    publish_rate: 50

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
cartesian_motor_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - x_axis_joint
        - y_axis_joint
        - z_axis_joint
        - yaw_joint
        - roll_joint
        - pitch_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        x_axis_joint: {trajectory: 0.1, goal: 0.1}
        y_axis_joint: {trajectory: 0.1, goal: 0.1}
        z_axis_joint: {trajectory: 0.1, goal: 0.1}
        yaw_joint: {trajectory: 0.1, goal: 0.1}
        roll_joint: {trajectory: 0.1, goal: 0.1}
        pitch_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
   #    #!!These values have not been optimized!!
        x_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        y_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        z_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        yaw_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        roll_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        pitch_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}

cartesian_motor_controller_wrist:
    type: position_controllers/JointTrajectoryController
    joints:
        - yaw_joint
        - roll_joint
        - pitch_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        yaw_joint: {trajectory: 0.1, goal: 0.1}
        roll_joint: {trajectory: 0.1, goal: 0.1}
        pitch_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
   #    #!!These values have not been optimized!!
        yaw_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        roll_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        pitch_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}

cartesian_motor_controller_sucker:
    type: position_controllers/JointTrajectoryController
    joints:
        - x_axis_joint
        - y_axis_joint
        - z_axis_joint
        - yaw_joint
        - roll_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        x_axis_joint: {trajectory: 0.1, goal: 0.1}
        y_axis_joint: {trajectory: 0.1, goal: 0.1}
        z_axis_joint: {trajectory: 0.1, goal: 0.1}
        yaw_joint: {trajectory: 0.1, goal: 0.1}
        roll_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
   #    #!!These values have not been optimized!!
        x_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        y_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        z_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        yaw_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        roll_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}

cartesian_motor_controller_realsense:
    type: position_controllers/JointTrajectoryController
    joints:
        - x_axis_joint
        - y_axis_joint
        - z_axis_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        x_axis_joint: {trajectory: 0.1, goal: 0.1}
        y_axis_joint: {trajectory: 0.1, goal: 0.1}
        z_axis_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    gains:
   #    #!!These values have not been optimized!!
        x_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        y_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
        z_axis_joint: {p: 10000.0,  i: 0.0, d: 0.01, i_clamp: 1}
